all: public01.x public02.x public03.x public04.x public05.x public06.x \
     public07.x public08.x public09.x public10.x public11.x public12.x \
     public13.x public14.x

public01.x:
	make -f Makefile.student public01.x

public02.x:
	make -f Makefile.student public02.x

public03.x:
	make -f Makefile.student public03.x

public04.x:
	make -f Makefile.student public04.x

public05.x:
	make -f Makefile.student public05.x

public06.x:
	make -f Makefile.student public06.x

public07.x:
	make -f Makefile.student public07.x

public08.x:
	make -f Makefile.student public08.x

public09.x:
	make -f Makefile.student public09.x

public10.x:
	make -f Makefile.student public10.x

public11.x:
	make -f Makefile.student public11.x

public12.x:
	make -f Makefile.student public12.x

public13.x:
	make -f Makefile.student public13.x

public14.x:
	make -f Makefile.student public14.x

clean:
	make -f Makefile.student clean
